"""added password

Revision ID: 216fb7ab35b5
Revises: 
Create Date: 2026-07-01 14:36:05.868528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216fb7ab35b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('card_number', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_users_card_number'), 'market_users', ['card_number'], unique=True)
    op.create_index(op.f('ix_market_users_id'), 'market_users', ['id'], unique=False)
    op.create_index(op.f('ix_market_users_password'), 'market_users', ['password'], unique=True)
    op.create_index(op.f('ix_market_users_username'), 'market_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_users_username'), table_name='market_users')
    op.drop_index(op.f('ix_market_users_password'), table_name='market_users')
    op.drop_index(op.f('ix_market_users_id'), table_name='market_users')
    op.drop_index(op.f('ix_market_users_card_number'), table_name='market_users')
    op.drop_table('market_users')
    # ### end Alembic commands ###
