"""card_number = str

Revision ID: 76d8ed58cd01
Revises: db6cf1e6a93e
Create Date: 2026-06-16 14:23:20.749898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d8ed58cd01'
down_revision: Union[str, Sequence[str], None] = 'db6cf1e6a93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_users_id'), table_name='market_users')
    op.drop_index(op.f('ix_market_users_username'), table_name='market_users')
    op.drop_table('market_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('market_users_pkey'))
    )
    op.create_index(op.f('ix_market_users_username'), 'market_users', ['username'], unique=True)
    op.create_index(op.f('ix_market_users_id'), 'market_users', ['id'], unique=False)
    # ### end Alembic commands ###
