"""card_number = str

Revision ID: cb481ed0f60d
Revises: 7ee9916609c7
Create Date: 2026-06-16 14:04:49.428799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb481ed0f60d'
down_revision: Union[str, Sequence[str], None] = '7ee9916609c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_users_id'), table_name='market_users')
    op.drop_table('market_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_users',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'username', 'card_number', name=op.f('market_users_pkey'))
    )
    op.create_index(op.f('ix_market_users_id'), 'market_users', ['id'], unique=False)
    # ### end Alembic commands ###
