services:
  app-service:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - app/.env
    network_mode: host

  user_app:
    build:
      context: .
      dockerfile: user_app/Dockerfile
    env_file:
      - user_app/.env
    network_mode: host

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    
    
  celery_worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A celery_app.currency worker --loglevel=INFO
    env_file:
      - ./celery_app/.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A celery_app.currency beat --loglevel=INFO
    env_file:
      - ./celery_app/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
