services:
  app-service:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - app/.env
    depends_on:
      redis:
        condition: service_started
    ports:
      - "8000:8000"

  user_app:
    build:
      context: .
      dockerfile: user_app/Dockerfile
    env_file:
      - user_app/.env
    depends_on:
      redis:
        condition: service_started
    ports:
      - "8001:8001"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A celery_app.currency worker --loglevel=INFO
    env_file:
      - ./celery_app/.env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A celery_app.currency beat --loglevel=INFO
    env_file:
      - ./celery_app/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-service
      - user_app

volumes:
  redis_data:
