"""check_sync

Revision ID: 272e8b276c03
Revises: b038f4bc3a75
Create Date: 2026-06-11 17:32:37.668930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272e8b276c03'
down_revision: Union[str, Sequence[str], None] = 'b038f4bc3a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
