"""made title ununique

Revision ID: 119e00ae9040
Revises: 
Create Date: 2026-06-20 18:16:19.888371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119e00ae9040'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=True)
    # ### end Alembic commands ###
