"""made title ununique

Revision ID: 2d90475839f0
Revises: f438783be903
Create Date: 2026-06-20 18:30:25.616348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d90475839f0'
down_revision: Union[str, Sequence[str], None] = 'f438783be903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=True)
    # ### end Alembic commands ###
