"""made title ununique

Revision ID: f1f2704df3a6
Revises: 
Create Date: 2026-06-20 18:11:21.612948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f2704df3a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_id'), table_name='market_product')
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.drop_table('market_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_product',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('market_product_pkey'))
    )
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=True)
    op.create_index(op.f('ix_market_product_id'), 'market_product', ['id'], unique=False)
    # ### end Alembic commands ###
