"""made title ununique

Revision ID: f438783be903
Revises: 119e00ae9040
Create Date: 2026-06-20 18:18:26.214082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f438783be903'
down_revision: Union[str, Sequence[str], None] = '119e00ae9040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_product_title'), table_name='market_product')
    op.create_index(op.f('ix_market_product_title'), 'market_product', ['title'], unique=False)
    # ### end Alembic commands ###
